### ISSUE TITLE
Loop importing prevents Infoset from starting

### ISSUE THREAD

**Issue by Jhamali** [PalisadoesFoundation/infosetDB#151]
Choose one: is this a bug report or feature request?

### Input Code

```python
def your_code():
    python3 docker/api.py
```

### Infoset Configuration (etc/config.yaml)

```yaml
{
main:
  db_file: ./infoset/db/infoset-db.db
  bind_port: 6000
  db_hostname: localhost
  db_name: infoset
  db_password: password
  db_username: root
  ingest_cache_directory: ./cache
  ingest_pool_size: 20
  interval: 60
  listen_address: 0.0.0.0
  log_directory: ./log
  log_level: debug
  log_file: infoset-ng.log
  memcached_hostname: localhost
  memcached_port: 11211
  redis_hostname: localhost
  redis_port: 6379
  sqlalchemy_max_overflow: 10
  sqlalchemy_pool_size: 10
  username: infoset

}
```

### Expected Behavior
Infoset server should start

### Current Behavior
Gives the following error:
Traceback (most recent call last):
  File "docker/api.py", line 16, in <module>
    from infoset.utils.configuration import Config
  File "/home/jhamali/infoset-ng/infoset/utils/configuration.py", line 8, in <module>
    from infoset.utils import general
  File "/home/jhamali/infoset-ng/infoset/utils/general.py", line 19, in <module>
    from infoset.utils import log
  File "/home/jhamali/infoset-ng/infoset/utils/log.py", line 14, in <module>
    from infoset.utils import configuration
ImportError: cannot import name configuration

### Context
Attempting to start infoset server

### Your Environment

| software         | version(s)
| ---------------- | -------
| infoset          |  2.1.0
| node             |  6.11.4
| npm              | 3.5.2
| Operating System | Ubuntu 17.1.0
