### ISSUE TITLE
Have to restart on code change

### ISSUE THREAD

**Issue by Jhamali** [PalisadoesFoundation/infosetDB#152]
Choose one:feature request

### Infoset Configuration (etc/config.yaml)

```yaml
{
 main:
  db_file: ./infoset/db/infoset-db.db
  bind_port: 6000
  db_hostname: localhost
  db_name: infoset
  db_password: password
  db_username: root
  ingest_cache_directory: ./cache
  ingest_pool_size: 20
  interval: 60
  listen_address: 0.0.0.0
  log_directory: ./log
  log_level: debug
  log_file: infoset-ng.log
  memcached_hostname: localhost
  memcached_port: 11211
  redis_hostname: localhost
  redis_port: 6379
  sqlalchemy_max_overflow: 10
  sqlalchemy_pool_size: 10
  username: infoset
}
```

### Expected Behavior
After a file is edited and saved, infoset should reload automatically with changes

### Current Behavior
After a file is edited and saved, infoset has to be closed and restarted to observe changes 

### Context
Slower testing having to constantly restart

### Your Environment

| software         | version(s)
| ---------------- | -------
| infoset          |  2.1.1
| node             | 4.2.6
| npm              | 3.5.2
| Operating System | Ubunutu 17.1
